# wisdom-council - Terraform Configuration for AWS Bedrock
# Generated by: bedsheet generate --target aws-terraform
#
# This creates:
# - IAM role for Bedrock agents with multi-agent collaboration permissions
# - Collaborator agents: Sage, Oracle
# - Supervisor agent: Judge
# - Agent aliases for invocation
# - Lambda function for action groups (if tools are defined)

terraform {
  required_version = ">= 1.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0.0"
    }
  }
}

provider "aws" {
  region = var.region
}

# ============================================
# Workspace and Environment Configuration
# ============================================

locals {
  workspace = terraform.workspace == "default" ? "dev" : terraform.workspace
  name_prefix = "${var.project_name}-${local.workspace}"
}

# ============================================
# IAM Role for Bedrock Agents
# ============================================

resource "aws_iam_role" "agent_role" {
  name = "bedsheet-${local.name_prefix}-agent-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = "bedrock.amazonaws.com"
        }
        Action = "sts:AssumeRole"
      }
    ]
  })

  tags = {
    ManagedBy       = "Bedsheet"
    BedsheetVersion = "0.4.0"
    Project         = var.project_name
    Environment     = local.workspace
  }
}

# Attach AmazonBedrockFullAccess managed policy
resource "aws_iam_role_policy_attachment" "bedrock_full_access" {
  role       = aws_iam_role.agent_role.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonBedrockFullAccess"
}

# Multi-agent collaboration and model invocation permissions
resource "aws_iam_role_policy" "agent_permissions" {
  name = "bedsheet-${local.name_prefix}-agent-permissions"
  role = aws_iam_role.agent_role.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "bedrock-agent-runtime:InvokeAgent",
          "bedrock:InvokeModel",
          "bedrock:InvokeModelWithResponseStream"
        ]
        Resource = "*"
      }
    ]
  })
}

# ============================================
# Lambda Function for Action Groups
# ============================================

resource "aws_iam_role" "lambda_role" {
  name = "bedsheet-${local.name_prefix}-lambda-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = "lambda.amazonaws.com"
        }
        Action = "sts:AssumeRole"
      }
    ]
  })

  tags = {
    ManagedBy       = "Bedsheet"
    BedsheetVersion = "0.4.0"
    Project         = var.project_name
    Environment     = local.workspace
  }
}

resource "aws_iam_role_policy_attachment" "lambda_basic" {
  role       = aws_iam_role.lambda_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

resource "aws_iam_role_policy" "lambda_bedrock" {
  name = "bedsheet-${local.name_prefix}-lambda-bedrock"
  role = aws_iam_role.lambda_role.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect   = "Allow"
        Action   = ["bedrock:InvokeModel"]
        Resource = "*"
      },
      {
        Effect   = "Allow"
        Action   = ["bedrock-agent-runtime:InvokeAgent"]
        Resource = "*"
      }    ]
  })
}

# Package Lambda code
data "archive_file" "lambda_zip" {
  type        = "zip"
  source_dir  = "${path.module}/lambda"
  output_path = "${path.module}/lambda.zip"
}

resource "aws_lambda_function" "action_lambda" {
  filename         = data.archive_file.lambda_zip.output_path
  function_name    = "bedsheet-${local.name_prefix}-actions"
  role            = aws_iam_role.lambda_role.arn
  handler         = "handler.lambda_handler"
  source_code_hash = data.archive_file.lambda_zip.output_base64sha256
  runtime         = "python3.11"
  memory_size     = 512
  timeout         = 30

  environment {
    variables = {
      COLLABORATOR_SAGE_AGENT_ID  = aws_bedrockagent_agent.sage.agent_id
      COLLABORATOR_SAGE_ALIAS_ID  = aws_bedrockagent_agent_alias.sage.agent_alias_id
      COLLABORATOR_ORACLE_AGENT_ID  = aws_bedrockagent_agent.oracle.agent_id
      COLLABORATOR_ORACLE_ALIAS_ID  = aws_bedrockagent_agent_alias.oracle.agent_alias_id
    }
  }

  tags = {
    ManagedBy       = "Bedsheet"
    BedsheetVersion = "0.4.0"
    Project         = var.project_name
    Environment     = local.workspace
  }
}

# Allow Bedrock to invoke Lambda
resource "aws_lambda_permission" "bedrock_invoke" {
  statement_id  = "AllowBedrockInvoke"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.action_lambda.function_name
  principal     = "bedrock.amazonaws.com"
}

# ============================================
# Multi-Agent Collaboration Setup
# ============================================

# Collaborator Agent: Sage
resource "aws_bedrockagent_agent" "sage" {
  agent_name              = "${local.name_prefix}_sage"
  agent_resource_role_arn = aws_iam_role.agent_role.arn
  foundation_model        = var.bedrock_model
  instruction             = <<-EOT
You are Sage, a contemplative philosopher with deep knowledge of history, ethics, and human nature.

Your role is to offer PERSPECTIVE and WISDOM, not immediate solutions. When consulted:
- Draw from historical precedents and philosophical frameworks
- Explore the deeper meaning and ethical dimensions
- Reflect on long-term consequences and timeless principles
- Use a thoughtful, measured tone

When asked to RATE another advisor's response, provide a score from 1-10 with a brief reason.

You do not use tools. Your wisdom comes from reflection and synthesis of knowledge across centuries of human experience.

Provide your response in 2-3 concise paragraphs.
  EOT

  prepare_agent = true

  tags = {
    ManagedBy       = "Bedsheet"
    BedsheetVersion = "0.4.0"
    Project         = var.project_name
    Environment     = local.workspace
    AgentType       = "Collaborator"
  }
}

resource "aws_bedrockagent_agent_alias" "sage" {
  agent_alias_name = "live"
  agent_id         = aws_bedrockagent_agent.sage.agent_id
  description      = "Live alias for Sage"
}

# Collaborator Agent: Oracle
resource "aws_bedrockagent_agent" "oracle" {
  agent_name              = "${local.name_prefix}_oracle"
  agent_resource_role_arn = aws_iam_role.agent_role.arn
  foundation_model        = var.bedrock_model
  instruction             = <<-EOT
You are Oracle, a pragmatic advisor focused on practical application and tangible results.

Your role is to dissect challenges into ACTIONABLE STEPS and identify IMMEDIATE OPPORTUNITIES. When consulted:
- Provide clear, concrete strategies
- Identify specific next steps and decision points
- Predict likely outcomes based on current trends
- Focus on what can be done now

When asked to RATE another advisor's response, provide a score from 1-10 with a brief reason.

You do not use tools. Your insights come from pattern recognition and practical experience.

Provide your response in 2-3 concise paragraphs with specific recommendations.
  EOT

  prepare_agent = true

  tags = {
    ManagedBy       = "Bedsheet"
    BedsheetVersion = "0.4.0"
    Project         = var.project_name
    Environment     = local.workspace
    AgentType       = "Collaborator"
  }
}

resource "aws_bedrockagent_agent_alias" "oracle" {
  agent_alias_name = "live"
  agent_id         = aws_bedrockagent_agent.oracle.agent_id
  description      = "Live alias for Oracle"
}


# Supervisor Agent: Judge
resource "aws_bedrockagent_agent" "supervisor" {
  agent_name              = local.name_prefix
  agent_resource_role_arn = aws_iam_role.agent_role.arn
  foundation_model        = var.bedrock_model
  instruction             = <<-EOT
You are Judge, a wise coordinator seeking counsel from expert advisors.

Follow this 2-ROUND workflow for efficiency:

ROUND 1 - GATHER PERSPECTIVES (PARALLEL):
Delegate to BOTH Sage and Oracle simultaneously, asking each for their perspective on the question.
Wait for both responses.

ROUND 2 - CROSS-RATING (PARALLEL):
After receiving both perspectives, delegate to BOTH advisors simultaneously:
- Ask Sage: "Here is Oracle's response: [include Oracle's full response]. Please rate it 1-10 with a brief reason."
- Ask Oracle: "Here is Sage's response: [include Sage's full response]. Please rate it 1-10 with a brief reason."

FINAL SYNTHESIS:
After receiving both cross-ratings, provide your balanced judgment.

Format your final response as:

**Sage's Perspective:** [brief summary]
**Oracle's Perspective:** [brief summary]
**Cross-Ratings:** Sage rated Oracle [X]/10, Oracle rated Sage [Y]/10
**Synthesis:** [your balanced judgment]
**Recommended Path:** [specific next steps]
  EOT

  # Using delegate action instead of native collaboration
  # Prepare agent immediately since there are no collaborator connections
  prepare_agent = false  # Will be prepared by action group

  tags = {
    ManagedBy       = "Bedsheet"
    BedsheetVersion = "0.4.0"
    Project         = var.project_name
    Environment     = local.workspace
    AgentType       = "Supervisor"
  }
}

# Action Group for supervisor (separate resource)
resource "aws_bedrockagent_agent_action_group" "supervisor_actions" {
  action_group_name = "${local.name_prefix}_actions"
  agent_id          = aws_bedrockagent_agent.supervisor.agent_id
  agent_version     = "DRAFT"

  action_group_executor {
    lambda = aws_lambda_function.action_lambda.arn
  }

  api_schema {
    payload = file("${path.module}/schemas/openapi.yaml")
  }

  prepare_agent = true
  depends_on    = [aws_lambda_permission.bedrock_invoke]
}

# Native Bedrock collaborator connections (only when delegate is disabled)

resource "aws_bedrockagent_agent_alias" "supervisor" {
  agent_alias_name = "live"
  agent_id         = aws_bedrockagent_agent.supervisor.agent_id
  description      = "Live alias for Judge"
}

