# wisdom-council - Terraform Outputs
# Generated by: bedsheet generate --target aws-terraform

# Supervisor Agent
output "supervisor_agent_id" {
  description = "ID of the supervisor agent"
  value       = aws_bedrockagent_agent.supervisor.agent_id
}

output "supervisor_alias_arn" {
  description = "ARN of the supervisor agent alias"
  value       = aws_bedrockagent_agent_alias.supervisor.agent_alias_arn
}

output "supervisor_alias_id" {
  description = "ID of the supervisor agent alias"
  value       = aws_bedrockagent_agent_alias.supervisor.agent_alias_id
}

# Collaborator Agents
output "sage_agent_id" {
  description = "ID of the Sage agent"
  value       = aws_bedrockagent_agent.sage.agent_id
}

output "sage_alias_arn" {
  description = "ARN of the Sage agent alias"
  value       = aws_bedrockagent_agent_alias.sage.agent_alias_arn
}
output "oracle_agent_id" {
  description = "ID of the Oracle agent"
  value       = aws_bedrockagent_agent.oracle.agent_id
}

output "oracle_alias_arn" {
  description = "ARN of the Oracle agent alias"
  value       = aws_bedrockagent_agent_alias.oracle.agent_alias_arn
}

