# wisdom-council - Terraform Variables Example
# Generated by: bedsheet generate --target aws-terraform
#
# Copy this file to terraform.tfvars and customize:
#   cp terraform.tfvars.example terraform.tfvars

project_name   = "wisdom_council"
region         = "eu-central-1"
bedrock_model  = "eu.anthropic.claude-sonnet-4-5-20250929-v1:0"