# wisdom-council - Terraform Variables
# Generated by: bedsheet generate --target aws-terraform

variable "project_name" {
  description = "Project name for resource naming"
  type        = string
  default     = "wisdom_council"
}

variable "region" {
  description = "AWS region for deployment"
  type        = string
  default     = "eu-central-1"
}

variable "bedrock_model" {
  description = "Bedrock foundation model ID"
  type        = string
  default     = "anthropic.claude-sonnet-4-5-20250929-v1:0"
}