#!/usr/bin/env python3
"""
wisdom-council - AWS CDK Application
Generated by: bedsheet deploy --target aws
"""
import aws_cdk as cdk

from stacks.agent_stack import AgentStack


app = cdk.App()

AgentStack(
    app,
    "WisdomcouncilStack",
    env=cdk.Environment(
        region="eu-central-1",
    ),
)

app.synth()