"""
wisdom-council - Bedrock Agent Stack
Generated by: bedsheet deploy --target aws
"""
from constructs import Construct
from aws_cdk import (
    Stack,
    Duration,
    RemovalPolicy,
    CfnOutput,
    aws_bedrock as bedrock,
    aws_lambda as lambda_,
    aws_iam as iam,
    aws_logs as logs,
)


class AgentStack(Stack):
    """CDK Stack for Judge Bedrock Agent."""

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # IAM role for Bedrock Agents
        agent_role = iam.Role(
            self, "AgentRole",
            assumed_by=iam.ServicePrincipal("bedrock.amazonaws.com"),
            managed_policies=[
                iam.ManagedPolicy.from_aws_managed_policy_name("AmazonBedrockFullAccess"),
            ],
        )

        # Multi-agent and model invocation permissions
        agent_role.add_to_policy(
            iam.PolicyStatement(
                actions=[
                    "bedrock-agent-runtime:InvokeAgent",
                    "bedrock:InvokeModel",
                    "bedrock:InvokeModelWithResponseStream"
                ],
                resources=["*"],
            )
        )

        # Lambda function for supervisor action groups
        action_lambda = lambda_.Function(
            self, "ActionLambda",
            runtime=lambda_.Runtime.PYTHON_3_11,
            handler="handler.lambda_handler",
            code=lambda_.Code.from_asset("lambda"),
            memory_size=512,
            timeout=Duration.seconds(30),
            log_retention=logs.RetentionDays.ONE_WEEK,
        )

        # Grant Bedrock permission to invoke Lambda
        action_lambda.grant_invoke(iam.ServicePrincipal("bedrock.amazonaws.com"))

        # Lambda execution role policy
        action_lambda.add_to_role_policy(
            iam.PolicyStatement(
                actions=["bedrock:InvokeModel"],
                resources=["*"],
            )
        )

        # ============================================
        # Multi-Agent Collaboration Setup
        # ============================================
        # Create collaborator agents first, then link to supervisor

        collaborator_aliases = {}

        # Collaborator: Sage
        sage_agent = bedrock.CfnAgent(
            self, "SageAgent",
            agent_name="wisdom_council_sage",
            agent_resource_role_arn=agent_role.role_arn,
            instruction="""You are Sage, a contemplative philosopher with deep knowledge of history, ethics, and human nature.\n\nYour role is to offer PERSPECTIVE and WISDOM, not immediate solutions. When consulted:\n- Draw from historical precedents and philosophical frameworks\n- Explore the deeper meaning and ethical dimensions\n- Reflect on long-term consequences and timeless principles\n- Use a thoughtful, measured tone\n\nWhen asked to RATE another advisor's response, provide a score from 1-10 with a brief reason.\n\nYou do not use tools. Your wisdom comes from reflection and synthesis of knowledge across centuries of human experience.\n\nProvide your response in 2-3 concise paragraphs.""",
            foundation_model="eu.anthropic.claude-sonnet-4-5-20250929-v1:0",
            auto_prepare=True,
        )

        sage_alias = bedrock.CfnAgentAlias(
            self, "SageAlias",
            agent_alias_name="live",
            agent_id=sage_agent.attr_agent_id,
        )
        collaborator_aliases["Sage"] = sage_alias

        # Collaborator: Oracle
        oracle_agent = bedrock.CfnAgent(
            self, "OracleAgent",
            agent_name="wisdom_council_oracle",
            agent_resource_role_arn=agent_role.role_arn,
            instruction="""You are Oracle, a pragmatic advisor focused on practical application and tangible results.\n\nYour role is to dissect challenges into ACTIONABLE STEPS and identify IMMEDIATE OPPORTUNITIES. When consulted:\n- Provide clear, concrete strategies\n- Identify specific next steps and decision points\n- Predict likely outcomes based on current trends\n- Focus on what can be done now\n\nWhen asked to RATE another advisor's response, provide a score from 1-10 with a brief reason.\n\nYou do not use tools. Your insights come from pattern recognition and practical experience.\n\nProvide your response in 2-3 concise paragraphs with specific recommendations.""",
            foundation_model="eu.anthropic.claude-sonnet-4-5-20250929-v1:0",
            auto_prepare=True,
        )

        oracle_alias = bedrock.CfnAgentAlias(
            self, "OracleAlias",
            agent_alias_name="live",
            agent_id=oracle_agent.attr_agent_id,
        )
        collaborator_aliases["Oracle"] = oracle_alias


        # Supervisor Agent with Multi-Agent Collaboration
        supervisor_agent = bedrock.CfnAgent(
            self, "SupervisorAgent",
            agent_name="wisdom_council",
            agent_resource_role_arn=agent_role.role_arn,
            instruction="""You are Judge, a wise coordinator seeking counsel from expert advisors.\n\nWhen you receive a question, consult both Sage and Oracle simultaneously for their perspectives.\nAfter receiving their insights, ask each to rate the other's response (1-10 with brief reason).\n\nBefore giving your final answer, reflect on what you learned from each advisor and their cross-ratings.\nThen provide your balanced judgment to the User.""",
            foundation_model="eu.anthropic.claude-sonnet-4-5-20250929-v1:0",
            action_groups=[
                bedrock.CfnAgent.AgentActionGroupProperty(
                    action_group_name="wisdom_council_actions",
                    action_group_executor=bedrock.CfnAgent.ActionGroupExecutorProperty(
                        lambda_=action_lambda.function_arn,
                    ),
                    api_schema=bedrock.CfnAgent.APISchemaProperty(
                        payload=open("schemas/openapi.yaml").read(),
                    ),
                ),
            ],
            # Enable multi-agent collaboration as supervisor
            agent_collaboration="SUPERVISOR",
            agent_collaborators=[
                bedrock.CfnAgent.AgentCollaboratorProperty(
                    collaborator_name="Sage",
                    agent_descriptor=bedrock.CfnAgent.AgentDescriptorProperty(
                        alias_arn=collaborator_aliases["Sage"].attr_agent_alias_arn,
                    ),
                    collaboration_instruction="""You are Sage, a contemplative philosopher with deep knowledge of history, ethics, and human nature.\n\nYour role is to offer PERSPECTIVE and WISDOM, not immediate solutions. When consulted:\n- Draw from historical precedents and philosophical frameworks\n- Explore the deeper meaning and ethical dimensions\n- Reflect on long-term consequences and timeless principles\n- Use a thoughtful, measured tone\n\nWhen asked to RATE another advisor's response, provide a score from 1-10 with a brief reason.\n\nYou do """,
                    relay_conversation_history="TO_COLLABORATOR",
                ),
                bedrock.CfnAgent.AgentCollaboratorProperty(
                    collaborator_name="Oracle",
                    agent_descriptor=bedrock.CfnAgent.AgentDescriptorProperty(
                        alias_arn=collaborator_aliases["Oracle"].attr_agent_alias_arn,
                    ),
                    collaboration_instruction="""You are Oracle, a pragmatic advisor focused on practical application and tangible results.\n\nYour role is to dissect challenges into ACTIONABLE STEPS and identify IMMEDIATE OPPORTUNITIES. When consulted:\n- Provide clear, concrete strategies\n- Identify specific next steps and decision points\n- Predict likely outcomes based on current trends\n- Focus on what can be done now\n\nWhen asked to RATE another advisor's response, provide a score from 1-10 with a brief reason.\n\nYou do not use tools. Your insi""",
                    relay_conversation_history="TO_COLLABORATOR",
                ),
            ],
            auto_prepare=True,
        )

        # Supervisor Agent Alias for invoking
        supervisor_alias = bedrock.CfnAgentAlias(
            self, "SupervisorAlias",
            agent_alias_name="live",
            agent_id=supervisor_agent.attr_agent_id,
        )

        # Outputs
        CfnOutput(self, "SupervisorAgentId", value=supervisor_agent.attr_agent_id)
        CfnOutput(self, "SupervisorAliasArn", value=supervisor_alias.attr_agent_alias_arn)
        CfnOutput(self, "SageAgentId", value=sage_agent.attr_agent_id)
        CfnOutput(self, "OracleAgentId", value=oracle_agent.attr_agent_id)

